name:             "The Manual: Blog"
description:      "Blog of The Manual, a design journal for the web."
permalink:        /:year/:month/:day/:title
url:              http://blog.themanual.org
rss_root:         http://blog.themanual.org/
rss_file:         posts.xml
rss_querystring: "?utm_source=rss&utm_medium=feed&utm_campaign=blog"
image_path:       /assets/img

markdown: kramdown
highlighter: pygments

include:  ['.htaccess']
exclude:  [
  'package.json',
  'bower.json',
  'node_modules',
  'bower_components',
  'README.md']